[profile.default]
fs_permissions = [{ access = "read-write", path = "./"}]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
evm_version = 'shanghai'
gas_limit = "100000000"   # very high limit for fork tests

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
fork = "http://127.0.0.1:8545"
