[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
evm_version = 'shanghai'
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
fork = "http://127.0.0.1:8545"